spring:
  aop:
    auto: off
  application:
    name: v2t-api

info:
  app:
    name: ${spring.application.name}
    version: "@application.version@"
    description: "@application.description@"

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO
    se:
      urvantsev:
        digpro: DEBUG


